pipeline {
    agent any
    stages {
        stage('Clean Up') {
            steps {
                sh 'ssh ubuntu@35.91.231.147 "rm -r simple-python-pyinstaller-app" '
            }
        }
        stage('Clone Repo') {
            steps {
                sh 'ssh ubuntu@35.91.231.147 "git clone https://github.com/z-prashansa-tiwari/simple-python-pyinstaller-app && sudo cp -r simple-python-pyinstaller-app /var/www"'
                echo 'Clone successfull'
            }
        }
        stage('Build') {
            steps {
                sh 'ssh ubuntu@35.91.231.147 python3 -m py_compile simple-python-pyinstaller-app/sources/add2vals.py sources/calc.py'        
            }
        }
        stage('Test') {
            steps {
                dir('simple-python-pyinstaller-app') {
                    sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            
                }
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                dir('simple-python-pyinstaller-app') {
                    sh 'pyinstaller --onefile sources/add2vals.py'
                }
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}
