pipeline {
    agent any
    stages {
        stage('Clean Up') {
            steps {
                sh 'ssh ubuntu@35.91.231.147 "rm -r simple-python-pyinstaller-app" '
            }
        }
        stage('Clone Repo') {
            steps {
                sh 'ssh ubuntu@35.91.231.147 "git clone https://github.com/z-prashansa-tiwari/simple-python-pyinstaller-app && sudo cp -r simple-python-pyinstaller-app /var/www"'
                echo 'Clone successfull'
            }
        }
        stage('Build') {
            steps {
                sh 'ssh ubuntu@35.91.231.147 "python3 -m py_compile simple-python-pyinstaller-app/sources/add2vals.py simple-python-pyinstaller-app/sources/calc.py"'        
            }
        }
        stage('Test') {
            steps {
                    sh 'ssh ubuntu@35.91.231.147 py.test --verbose --junit-xml test-reports/results.xml simple-python-pyinstaller-app/sources/test_calc.py'
            }
            post {
                always {
                    junit 'ssh ubuntu@35.91.231.147 test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                    sh 'ssh ubuntu@35.91.231.147 pyinstaller --onefile simple-python-pyinstaller-app/sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}
